kind: Deployment
apiVersion: apps/v1
metadata:
# set your lab user name
  name: {{ .Release.Name }}    #user12-hello-world
spec:
  replicas: {{ .Values.ReplicaNumber }}  #3
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels: 
# set your lab user name
        app: {{ .Release.Name }} #user12-hello-world
    spec:
      volumes:
        - name: index-html
          configMap:
            name: index.html
            defaultMode: 420
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: {{ .Release.Name }}  #hello-world
          ports:
            - containerPort: {{ .Values.containers.containerPort }} #8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
# update with the image you build in part 1
          image: {{ .Values.containers.image }}:{{ .Values.containers.tag }} #'quay.io/redhatuser82/myimagename:v3'
          volumeMounts:
            - name: index-html
              mountPath: /tmp/html # this will mount the html.index file to it application location  
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10