ReplicaNumber: 3

containers:
  containerPort: 8080
  image: 'quay.io/redhatuser82/myimagename'
  tag: 'v3'

service::

  servicePort: 8080
probes:
  readiness:
    path:
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  liveness:
    path:
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
volume:
  mount:
    path: /tmp/html
